{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "secrets-bridge-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets-bridge-agent.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "secrets-bridge-agent.selectorLabels" . | nindent 6 }}
{{- end -}}
