{{- if and .Values.api.enabled .Values.api.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "secrets-bridge.componentName" (dict "ctx" . "component" "api") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets-bridge.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "secrets-bridge.componentSelectorLabels" (dict "ctx" . "component" "api") | nindent 6 }}
{{- end -}}
