{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "secrets-bridge.componentName" (dict "ctx" . "component" "ui") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets-bridge.componentLabels" (dict "ctx" . "component" "ui") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ui.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "secrets-bridge.componentSelectorLabels" (dict "ctx" . "component" "ui") | nindent 4 }}
{{- end -}}
