{{- if and .Values.worker.enabled .Values.worker.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "secrets-bridge.componentName" (dict "ctx" . "component" "worker") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets-bridge.componentLabels" (dict "ctx" . "component" "worker") | nindent 4 }}
spec:
  minAvailable: {{ .Values.worker.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "secrets-bridge.componentSelectorLabels" (dict "ctx" . "component" "worker") | nindent 6 }}
{{- end -}}
