{{- if and .Values.worker.enabled .Values.worker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secrets-bridge.componentServiceAccountName" (dict "ctx" . "component" "worker" "spec" .Values.worker.serviceAccount) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets-bridge.componentLabels" (dict "ctx" . "component" "worker") | nindent 4 }}
  {{- with .Values.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.worker.serviceAccount.automountServiceAccountToken }}
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
